[package]
name = "unbounded-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
root = { path = "../root" }
tokio = { version = "1", features = ["full"] }
futures = "0.3.28"
